eureka:
  client:
    serviceUrl:
      #defaultZone: http://116.196.84.163:8761/eureka
      #defaultZone: http://114.67.88.237:8761/eureka/
      defaultZone: http://192.168.0.121:30115/eureka/,http://192.168.0.16:30115/eureka/
  instance:
    preferIpAddress: true
  register-with-eureka: true




